// Auto-generated from assets/stickers - do not edit paths by hand.
// Add new PNGs under assets/stickers/... and run: find assets/stickers -name '*.png' | sort
class StickerItem {
  final String name;
  final String assetPath;

  const StickerItem({
    required this.name,
    required this.assetPath,
  });

  static const List<String> _assetPaths = [
    'assets/stickers/Arrow/Arrow (1).png',
    'assets/stickers/Arrow/Arrow (10).png',
    'assets/stickers/Arrow/Arrow (11).png',
    'assets/stickers/Arrow/Arrow (12).png',
    'assets/stickers/Arrow/Arrow (13).png',
    'assets/stickers/Arrow/Arrow (14).png',
    'assets/stickers/Arrow/Arrow (15).png',
    'assets/stickers/Arrow/Arrow (16).png',
    'assets/stickers/Arrow/Arrow (17).png',
    'assets/stickers/Arrow/Arrow (18).png',
    'assets/stickers/Arrow/Arrow (19).png',
    'assets/stickers/Arrow/Arrow (2).png',
    'assets/stickers/Arrow/Arrow (20).png',
    'assets/stickers/Arrow/Arrow (21).png',
    'assets/stickers/Arrow/Arrow (3).png',
    'assets/stickers/Arrow/Arrow (4).png',
    'assets/stickers/Arrow/Arrow (5).png',
    'assets/stickers/Arrow/Arrow (6).png',
    'assets/stickers/Arrow/Arrow (7).png',
    'assets/stickers/Arrow/Arrow (8).png',
    'assets/stickers/Arrow/Arrow (9).png',
    'assets/stickers/Arrow/Asset 10@5x.png',
    'assets/stickers/Arrow/Asset 11@5x.png',
    'assets/stickers/Arrow/Asset 12@5x.png',
    'assets/stickers/Arrow/Asset 17@5x.png',
    'assets/stickers/Arrow/Asset 18@5x.png',
    'assets/stickers/Arrow/Asset 19@5x.png',
    'assets/stickers/Arrow/Asset 1@5x.png',
    'assets/stickers/Arrow/Asset 20@5x.png',
    'assets/stickers/Arrow/Asset 21@5x.png',
    'assets/stickers/Arrow/Asset 22@5x.png',
    'assets/stickers/Arrow/Asset 23@5x.png',
    'assets/stickers/Arrow/Asset 2@5x.png',
    'assets/stickers/Arrow/Asset 3@5x.png',
    'assets/stickers/Arrow/Asset 4@5x.png',
    'assets/stickers/Arrow/Asset 5@5x.png',
    'assets/stickers/Arrow/Asset 6@5x.png',
    'assets/stickers/Arrow/Asset 7@5x.png',
    'assets/stickers/Arrow/Asset 8@5x.png',
    'assets/stickers/Arrow/Asset 9@5x.png',
    'assets/stickers/Emoji/Emoji (1).png',
    'assets/stickers/Emoji/Emoji (10).png',
    'assets/stickers/Emoji/Emoji (11).png',
    'assets/stickers/Emoji/Emoji (12).png',
    'assets/stickers/Emoji/Emoji (13).png',
    'assets/stickers/Emoji/Emoji (14).png',
    'assets/stickers/Emoji/Emoji (15).png',
    'assets/stickers/Emoji/Emoji (16).png',
    'assets/stickers/Emoji/Emoji (17).png',
    'assets/stickers/Emoji/Emoji (18).png',
    'assets/stickers/Emoji/Emoji (19).png',
    'assets/stickers/Emoji/Emoji (2).png',
    'assets/stickers/Emoji/Emoji (20).png',
    'assets/stickers/Emoji/Emoji (21).png',
    'assets/stickers/Emoji/Emoji (22).png',
    'assets/stickers/Emoji/Emoji (23).png',
    'assets/stickers/Emoji/Emoji (24).png',
    'assets/stickers/Emoji/Emoji (25).png',
    'assets/stickers/Emoji/Emoji (26).png',
    'assets/stickers/Emoji/Emoji (27).png',
    'assets/stickers/Emoji/Emoji (28).png',
    'assets/stickers/Emoji/Emoji (29).png',
    'assets/stickers/Emoji/Emoji (3).png',
    'assets/stickers/Emoji/Emoji (30).png',
    'assets/stickers/Emoji/Emoji (31).png',
    'assets/stickers/Emoji/Emoji (32).png',
    'assets/stickers/Emoji/Emoji (33).png',
    'assets/stickers/Emoji/Emoji (34).png',
    'assets/stickers/Emoji/Emoji (35).png',
    'assets/stickers/Emoji/Emoji (36).png',
    'assets/stickers/Emoji/Emoji (37).png',
    'assets/stickers/Emoji/Emoji (38).png',
    'assets/stickers/Emoji/Emoji (39).png',
    'assets/stickers/Emoji/Emoji (4).png',
    'assets/stickers/Emoji/Emoji (40).png',
    'assets/stickers/Emoji/Emoji (41).png',
    'assets/stickers/Emoji/Emoji (42).png',
    'assets/stickers/Emoji/Emoji (43).png',
    'assets/stickers/Emoji/Emoji (44).png',
    'assets/stickers/Emoji/Emoji (45).png',
    'assets/stickers/Emoji/Emoji (46).png',
    'assets/stickers/Emoji/Emoji (47).png',
    'assets/stickers/Emoji/Emoji (48).png',
    'assets/stickers/Emoji/Emoji (49).png',
    'assets/stickers/Emoji/Emoji (5).png',
    'assets/stickers/Emoji/Emoji (50).png',
    'assets/stickers/Emoji/Emoji (51).png',
    'assets/stickers/Emoji/Emoji (52).png',
    'assets/stickers/Emoji/Emoji (53).png',
    'assets/stickers/Emoji/Emoji (54).png',
    'assets/stickers/Emoji/Emoji (55).png',
    'assets/stickers/Emoji/Emoji (6).png',
    'assets/stickers/Emoji/Emoji (7).png',
    'assets/stickers/Emoji/Emoji (8).png',
    'assets/stickers/Emoji/Emoji (9).png',
    'assets/stickers/Frame/Frame (1).png',
    'assets/stickers/Frame/Frame (10).png',
    'assets/stickers/Frame/Frame (11).png',
    'assets/stickers/Frame/Frame (12).png',
    'assets/stickers/Frame/Frame (13).png',
    'assets/stickers/Frame/Frame (14).png',
    'assets/stickers/Frame/Frame (15).png',
    'assets/stickers/Frame/Frame (16).png',
    'assets/stickers/Frame/Frame (17).png',
    'assets/stickers/Frame/Frame (18).png',
    'assets/stickers/Frame/Frame (19).png',
    'assets/stickers/Frame/Frame (2).png',
    'assets/stickers/Frame/Frame (20).png',
    'assets/stickers/Frame/Frame (21).png',
    'assets/stickers/Frame/Frame (22).png',
    'assets/stickers/Frame/Frame (23).png',
    'assets/stickers/Frame/Frame (24).png',
    'assets/stickers/Frame/Frame (25).png',
    'assets/stickers/Frame/Frame (3).png',
    'assets/stickers/Frame/Frame (4).png',
    'assets/stickers/Frame/Frame (5).png',
    'assets/stickers/Frame/Frame (6).png',
    'assets/stickers/Frame/Frame (7).png',
    'assets/stickers/Frame/Frame (8).png',
    'assets/stickers/Frame/Frame (9).png',
    'assets/stickers/Like/Like (1).png',
    'assets/stickers/Like/Like (10).png',
    'assets/stickers/Like/Like (11).png',
    'assets/stickers/Like/Like (12).png',
    'assets/stickers/Like/Like (13).png',
    'assets/stickers/Like/Like (14).png',
    'assets/stickers/Like/Like (15).png',
    'assets/stickers/Like/Like (16).png',
    'assets/stickers/Like/Like (17).png',
    'assets/stickers/Like/Like (18).png',
    'assets/stickers/Like/Like (19).png',
    'assets/stickers/Like/Like (2).png',
    'assets/stickers/Like/Like (20).png',
    'assets/stickers/Like/Like (3).png',
    'assets/stickers/Like/Like (4).png',
    'assets/stickers/Like/Like (5).png',
    'assets/stickers/Like/Like (6).png',
    'assets/stickers/Like/Like (7).png',
    'assets/stickers/Like/Like (8).png',
    'assets/stickers/Like/Like (9).png',
    'assets/stickers/Memes/Memes (1).png',
    'assets/stickers/Memes/Memes (10).png',
    'assets/stickers/Memes/Memes (11).png',
    'assets/stickers/Memes/Memes (12).png',
    'assets/stickers/Memes/Memes (13).png',
    'assets/stickers/Memes/Memes (14).png',
    'assets/stickers/Memes/Memes (15).png',
    'assets/stickers/Memes/Memes (16).png',
    'assets/stickers/Memes/Memes (17).png',
    'assets/stickers/Memes/Memes (18).png',
    'assets/stickers/Memes/Memes (19).png',
    'assets/stickers/Memes/Memes (2).png',
    'assets/stickers/Memes/Memes (20).png',
    'assets/stickers/Memes/Memes (21).png',
    'assets/stickers/Memes/Memes (22).png',
    'assets/stickers/Memes/Memes (23).png',
    'assets/stickers/Memes/Memes (24).png',
    'assets/stickers/Memes/Memes (25).png',
    'assets/stickers/Memes/Memes (26).png',
    'assets/stickers/Memes/Memes (27).png',
    'assets/stickers/Memes/Memes (28).png',
    'assets/stickers/Memes/Memes (29).png',
    'assets/stickers/Memes/Memes (3).png',
    'assets/stickers/Memes/Memes (30).png',
    'assets/stickers/Memes/Memes (31).png',
    'assets/stickers/Memes/Memes (32).png',
    'assets/stickers/Memes/Memes (33).png',
    'assets/stickers/Memes/Memes (34).png',
    'assets/stickers/Memes/Memes (35).png',
    'assets/stickers/Memes/Memes (36).png',
    'assets/stickers/Memes/Memes (37).png',
    'assets/stickers/Memes/Memes (38).png',
    'assets/stickers/Memes/Memes (39).png',
    'assets/stickers/Memes/Memes (4).png',
    'assets/stickers/Memes/Memes (40).png',
    'assets/stickers/Memes/Memes (41).png',
    'assets/stickers/Memes/Memes (42).png',
    'assets/stickers/Memes/Memes (43).png',
    'assets/stickers/Memes/Memes (44).png',
    'assets/stickers/Memes/Memes (45).png',
    'assets/stickers/Memes/Memes (46).png',
    'assets/stickers/Memes/Memes (47).png',
    'assets/stickers/Memes/Memes (48).png',
    'assets/stickers/Memes/Memes (49).png',
    'assets/stickers/Memes/Memes (5).png',
    'assets/stickers/Memes/Memes (50).png',
    'assets/stickers/Memes/Memes (51).png',
    'assets/stickers/Memes/Memes (52).png',
    'assets/stickers/Memes/Memes (53).png',
    'assets/stickers/Memes/Memes (54).png',
    'assets/stickers/Memes/Memes (55).png',
    'assets/stickers/Memes/Memes (56).png',
    'assets/stickers/Memes/Memes (57).png',
    'assets/stickers/Memes/Memes (58).png',
    'assets/stickers/Memes/Memes (6).png',
    'assets/stickers/Memes/Memes (7).png',
    'assets/stickers/Memes/Memes (8).png',
    'assets/stickers/Memes/Memes (9).png',
    'assets/stickers/Nowruz/Asset 10@6x.png',
    'assets/stickers/Nowruz/Asset 11@6x.png',
    'assets/stickers/Nowruz/Asset 12@7x.png',
    'assets/stickers/Nowruz/Asset 13@6x.png',
    'assets/stickers/Nowruz/Asset 1@5x.png',
    'assets/stickers/Nowruz/Asset 2@5x.png',
    'assets/stickers/Nowruz/Asset 3@5x.png',
    'assets/stickers/Nowruz/Asset 4@5x.png',
    'assets/stickers/Nowruz/Asset 6@12x.png',
    'assets/stickers/Nowruz/Asset 7@12x.png',
    'assets/stickers/Nowruz/Asset 8@6x.png',
    'assets/stickers/Nowruz/Asset 9@7x.png',
    'assets/stickers/Nowruz/N (13).png',
    'assets/stickers/Nowruz/N (14).png',
    'assets/stickers/Nowruz/N (15).png',
    'assets/stickers/Nowruz/N (16).png',
    'assets/stickers/Nowruz/N (17).png',
    'assets/stickers/Nowruz/N (18).png',
    'assets/stickers/Nowruz/N (19).png',
    'assets/stickers/Nowruz/N (20).png',
    'assets/stickers/Nowruz/N (21).png',
    'assets/stickers/Nowruz/N (22).png',
    'assets/stickers/Nowruz/N (23).png',
    'assets/stickers/Nowruz/N (24).png',
    'assets/stickers/Nowruz/N (25).png',
    'assets/stickers/Nowruz/N (26).png',
    'assets/stickers/Nowruz/N (27).png',
    'assets/stickers/Nowruz/N (28).png',
    'assets/stickers/Nowruz/N (29).png',
    'assets/stickers/Nowruz/N (30).png',
    'assets/stickers/Nowruz/N (31).png',
    'assets/stickers/Nowruz/N (32).png',
    'assets/stickers/Nowruz/N (33).png',
    'assets/stickers/Nowruz/N (34).png',
    'assets/stickers/Nowruz/N (35).png',
    'assets/stickers/Nowruz/N (36).png',
    'assets/stickers/Nowruz/N (37).png',
    'assets/stickers/Nowruz/N (39).png',
    'assets/stickers/Nowruz/N (40).png',
    'assets/stickers/Nowruz/N (41).png',
    'assets/stickers/Nowruz/N (42).png',
    'assets/stickers/Nowruz/N (43).png',
    'assets/stickers/Nowruz/N (44).png',
    'assets/stickers/Nowruz/N (45).png',
    'assets/stickers/Nowruz/N (46).png',
    'assets/stickers/Nowruz/N (47).png',
    'assets/stickers/Nowruz/N (48).png',
    'assets/stickers/Nowruz/N (49).png',
    'assets/stickers/Nowruz/N (50).png',
    'assets/stickers/Nowruz/N (51).png',
    'assets/stickers/Nowruz/N (53).png',
    'assets/stickers/Nowruz/N (54).png',
    'assets/stickers/Nowruz/N (55).png',
    'assets/stickers/Sale/Sale (1).png',
    'assets/stickers/Sale/Sale (10).png',
    'assets/stickers/Sale/Sale (11).png',
    'assets/stickers/Sale/Sale (12).png',
    'assets/stickers/Sale/Sale (13).png',
    'assets/stickers/Sale/Sale (14).png',
    'assets/stickers/Sale/Sale (15).png',
    'assets/stickers/Sale/Sale (16).png',
    'assets/stickers/Sale/Sale (17).png',
    'assets/stickers/Sale/Sale (18).png',
    'assets/stickers/Sale/Sale (19).png',
    'assets/stickers/Sale/Sale (2).png',
    'assets/stickers/Sale/Sale (20).png',
    'assets/stickers/Sale/Sale (21).png',
    'assets/stickers/Sale/Sale (22).png',
    'assets/stickers/Sale/Sale (23).png',
    'assets/stickers/Sale/Sale (24).png',
    'assets/stickers/Sale/Sale (3).png',
    'assets/stickers/Sale/Sale (4).png',
    'assets/stickers/Sale/Sale (5).png',
    'assets/stickers/Sale/Sale (6).png',
    'assets/stickers/Sale/Sale (7).png',
    'assets/stickers/Sale/Sale (8).png',
    'assets/stickers/Sale/Sale (9).png',
    'assets/stickers/Social Media/Social Media (1).png',
    'assets/stickers/Social Media/Social Media (10).png',
    'assets/stickers/Social Media/Social Media (11).png',
    'assets/stickers/Social Media/Social Media (12).png',
    'assets/stickers/Social Media/Social Media (13).png',
    'assets/stickers/Social Media/Social Media (14).png',
    'assets/stickers/Social Media/Social Media (15).png',
    'assets/stickers/Social Media/Social Media (16).png',
    'assets/stickers/Social Media/Social Media (17).png',
    'assets/stickers/Social Media/Social Media (18).png',
    'assets/stickers/Social Media/Social Media (19).png',
    'assets/stickers/Social Media/Social Media (2).png',
    'assets/stickers/Social Media/Social Media (20).png',
    'assets/stickers/Social Media/Social Media (21).png',
    'assets/stickers/Social Media/Social Media (3).png',
    'assets/stickers/Social Media/Social Media (4).png',
    'assets/stickers/Social Media/Social Media (5).png',
    'assets/stickers/Social Media/Social Media (6).png',
    'assets/stickers/Social Media/Social Media (7).png',
    'assets/stickers/Social Media/Social Media (8).png',
    'assets/stickers/Social Media/Social Media (9).png',
  ];

  static List<StickerItem> get allStickers => _assetPaths.asMap().entries
      .map((e) => StickerItem(name: 'sticker_${e.key}', assetPath: e.value))
      .toList();
}
