import 'package:flutter/material.dart';

class TextStylePreset {
  final String id;
  final String name;
  final String displayName;
  final Color textColor;
  final Color? strokeColor;
  final double? strokeWidth;
  final Color? shadowColor;
  final Offset? shadowOffset;
  final double? shadowBlur;
  final Color? backgroundColor;
  final List<Color>? gradientColors;
  final String? previewAsset;
  final String? fontFamily;
  final double? fontSize;
  final FontWeight? fontWeight;
  // Canvas (page) background applied when the preset is selected.
  final Color? canvasColor;
  final List<Color>? canvasGradient;
  final List<double>? canvasGradientStops;
  final bool hasBubble;
  final bool isPro;

  const TextStylePreset({
    required this.id,
    required this.name,
    required this.displayName,
    this.textColor = Colors.white,
    this.strokeColor,
    this.strokeWidth,
    this.shadowColor,
    this.shadowOffset,
    this.shadowBlur,
    this.backgroundColor,
    this.gradientColors,
    this.previewAsset,
    this.fontFamily,
    this.fontSize,
    this.fontWeight,
    this.canvasColor,
    this.canvasGradient,
    this.canvasGradientStops,
    this.hasBubble = false,
    this.isPro = false,
  });

  /// Presets loaded at runtime from Figma local text styles (optional).
  static List<TextStylePreset> figmaPresets = const [];

  /// All presets shown in the style picker.
  ///
  /// These 30 presets are imported from the Figma "Text effects Pishrafte"
  /// community file. The preview cards use the original Figma renders, while
  /// the canvas applies the matching font, colors, stroke, shadow and page
  /// background through the existing Flutter text pipeline.
  static List<TextStylePreset> get allPresets => [
        ...pishraftePresets,
        ...figmaPresets,
      ];

  static const List<TextStylePreset> pishraftePresets = [
    TextStylePreset(
      id: 'comic',
      name: 'Comic',
      displayName: 'Comic',
      fontFamily: 'Bangers',
      fontWeight: FontWeight.w400,
      textColor: Color(0xFFFDE601),
      strokeColor: Color(0xFF000000),
      strokeWidth: 2.5,
      shadowColor: Color(0x33000000),
      shadowOffset: Offset(6, 6),
      shadowBlur: 0.0,
      canvasColor: Color(0xFFEF2A2B),
      previewAsset: 'assets/styles/pishrafte/comic.png',
    ),
    TextStylePreset(
      id: 'abyss',
      name: 'Abyss',
      displayName: 'Abyss',
      fontFamily: 'Cairo',
      fontWeight: FontWeight.w900,
      textColor: Color(0xFF2A1466),
      shadowColor: Color(0x33FFFFFF),
      shadowOffset: Offset(2, 2),
      shadowBlur: 2.0,
      canvasGradient: [Color(0xFF652EDB), Color(0xFF331196)],
      previewAsset: 'assets/styles/pishrafte/abyss.png',
    ),
    TextStylePreset(
      id: 'milk',
      name: 'Milk',
      displayName: 'Milk',
      fontFamily: 'LeckerliOne',
      fontWeight: FontWeight.w400,
      textColor: Colors.white,
      strokeColor: Color(0xFF000000),
      strokeWidth: 2.0,
      shadowColor: Color(0x66000000),
      shadowOffset: Offset(2, 4),
      shadowBlur: 6.0,
      canvasColor: Color(0xFFFFFFFF),
      previewAsset: 'assets/styles/pishrafte/milk.png',
    ),
    TextStylePreset(
      id: 'laser',
      name: 'Laser',
      displayName: 'Laser',
      fontFamily: 'ZenDots',
      fontWeight: FontWeight.w400,
      textColor: Color(0xFFFF4F37),
      shadowColor: Color(0xFFFF3557),
      shadowOffset: Offset(0, 0),
      shadowBlur: 18.0,
      canvasColor: Color(0xFF090B25),
      previewAsset: 'assets/styles/pishrafte/laser.png',
    ),
    TextStylePreset(
      id: 'holo',
      name: 'Holo',
      displayName: 'Holo',
      fontFamily: 'Staatliches',
      fontWeight: FontWeight.w400,
      textColor: Color(0xFFF93995),
      gradientColors: [Color(0xFFFF7ACB), Color(0xFFB851FF), Color(0xFF47D7FF)],
      shadowColor: Color(0xAA7B2CFF),
      shadowOffset: Offset(4, 8),
      shadowBlur: 16.0,
      canvasGradient: [Color(0xFF13002C), Color(0xFF4A003A)],
      previewAsset: 'assets/styles/pishrafte/holo.png',
    ),
    TextStylePreset(
      id: 'flare',
      name: 'Flare',
      displayName: 'Flare',
      fontFamily: 'Oswald',
      fontWeight: FontWeight.w700,
      textColor: Color(0xFF0C3A4C),
      gradientColors: [Color(0xFF0E5C78), Color(0xFF00B5FF)],
      shadowColor: Color(0xAA00B5FF),
      shadowOffset: Offset(2, 8),
      shadowBlur: 18.0,
      canvasColor: Color(0xFF02151E),
      previewAsset: 'assets/styles/pishrafte/flare.png',
    ),
    TextStylePreset(
      id: 'cloud',
      name: 'Cloud',
      displayName: 'Cloud',
      fontFamily: 'Comfortaa',
      fontWeight: FontWeight.w300,
      textColor: Colors.white,
      shadowColor: Color(0xCCFFFFFF),
      shadowOffset: Offset(0, 0),
      shadowBlur: 18.0,
      canvasGradient: [Color(0xFF0038FF), Color(0xFF00C2FF)],
      previewAsset: 'assets/styles/pishrafte/cloud.png',
    ),
    TextStylePreset(
      id: 'wallsign',
      name: 'Wallsign',
      displayName: 'Wallsign',
      fontFamily: 'Oswald',
      fontWeight: FontWeight.w600,
      textColor: Color(0xFF333333),
      shadowColor: Color(0x80000000),
      shadowOffset: Offset(6, 10),
      shadowBlur: 10.0,
      canvasGradient: [Color(0xFFF4F4F4), Color(0xFF898989)],
      previewAsset: 'assets/styles/pishrafte/wallsign.png',
    ),
    TextStylePreset(
      id: 'summer',
      name: 'Summer',
      displayName: 'Summer',
      fontFamily: 'Nunito',
      fontWeight: FontWeight.w900,
      textColor: Color(0xFFF6206D),
      strokeColor: Colors.white,
      strokeWidth: 3.0,
      shadowColor: Color(0x33000000),
      shadowOffset: Offset(6, 6),
      shadowBlur: 0.0,
      canvasColor: Color(0xFF2EFFCD),
      previewAsset: 'assets/styles/pishrafte/summer.png',
    ),
    TextStylePreset(
      id: 'noir',
      name: 'Noir',
      displayName: 'Noir',
      fontFamily: 'AShams',
      fontWeight: FontWeight.w400,
      textColor: Color(0xFF8E8E8E),
      strokeColor: Color(0xFF111111),
      strokeWidth: 1.5,
      shadowColor: Color(0x99000000),
      shadowOffset: Offset(3, 7),
      shadowBlur: 12.0,
      canvasGradient: [Color(0xFF2B2B2B), Color(0xFF0F0F0F)],
      previewAsset: 'assets/styles/pishrafte/noir.png',
    ),
    TextStylePreset(
      id: 'pin_up',
      name: 'Pin-up',
      displayName: 'Pin-up',
      fontFamily: 'AAtila',
      fontWeight: FontWeight.w700,
      textColor: Color(0xFFE94A38),
      strokeColor: Color(0xFF1A1A1A),
      strokeWidth: 1.4,
      shadowColor: Color(0x88000000),
      shadowOffset: Offset(3, 5),
      shadowBlur: 4.0,
      canvasGradient: [Color(0xFF68B5C1), Color(0xFF388F9D)],
      previewAsset: 'assets/styles/pishrafte/pin_up.png',
    ),
    TextStylePreset(
      id: 'groovy',
      name: 'Groovy',
      displayName: 'Groovy',
      fontFamily: 'FugazOne',
      fontWeight: FontWeight.w400,
      textColor: Color(0xFFD58C32),
      strokeColor: Color(0xFF2E5B21),
      strokeWidth: 1.2,
      shadowColor: Color(0x66000000),
      shadowOffset: Offset(2, 4),
      shadowBlur: 4.0,
      canvasColor: Color(0xFF7F9A59),
      previewAsset: 'assets/styles/pishrafte/groovy.png',
    ),
    TextStylePreset(
      id: 'quartz',
      name: 'Quartz',
      displayName: 'Quartz',
      fontFamily: 'Roboto',
      fontWeight: FontWeight.w900,
      textColor: Color(0xFFE1E1E1),
      shadowColor: Color(0x66000000),
      shadowOffset: Offset(4, 8),
      shadowBlur: 12.0,
      canvasColor: Color(0xFFD9D9D9),
      previewAsset: 'assets/styles/pishrafte/quartz.png',
    ),
    TextStylePreset(
      id: 'gold',
      name: 'Gold',
      displayName: 'Gold',
      fontFamily: 'RedHatDisplay',
      fontWeight: FontWeight.w700,
      textColor: Color(0xFFDCB362),
      gradientColors: [Color(0xFFDCB362), Color(0xFFB8860B)],
      shadowColor: Color(0x33000000),
      shadowOffset: Offset(0, 8),
      shadowBlur: 16.0,
      canvasColor: Color(0xFF1A162E),
      previewAsset: 'assets/styles/pishrafte/gold.png',
    ),
    TextStylePreset(
      id: 'concrete',
      name: 'Concrete',
      displayName: 'Concrete',
      fontFamily: 'Oxanium',
      fontWeight: FontWeight.w800,
      textColor: Color(0xFFE34949),
      shadowColor: Color(0x66000000),
      shadowOffset: Offset(8, 12),
      shadowBlur: 8.0,
      canvasColor: Color(0xFF2B2B2B),
      previewAsset: 'assets/styles/pishrafte/concrete.png',
    ),
    TextStylePreset(
      id: 'vintage',
      name: 'Vintage',
      displayName: 'Vintage',
      fontFamily: 'AArghavan',
      fontWeight: FontWeight.w700,
      textColor: Color(0xFFD33F86),
      strokeColor: Color(0xFFF4F4F4),
      strokeWidth: 1.8,
      shadowColor: Color(0x66000000),
      shadowOffset: Offset(3, 8),
      shadowBlur: 12.0,
      canvasGradient: [Color(0xFF4487D4), Color(0xFF3A60E4)],
      previewAsset: 'assets/styles/pishrafte/vintage.png',
    ),
    TextStylePreset(
      id: 'pop_art',
      name: 'Pop art',
      displayName: 'Pop art',
      fontFamily: 'ArchivoBlack',
      fontWeight: FontWeight.w900,
      textColor: Color(0xFF24D6E6),
      strokeColor: Colors.white,
      strokeWidth: 1.8,
      shadowColor: Color(0xAA4C2EA8),
      shadowOffset: Offset(4, 6),
      shadowBlur: 0.0,
      canvasColor: Color(0xFFFF2D91),
      previewAsset: 'assets/styles/pishrafte/pop_art.png',
    ),
    TextStylePreset(
      id: 'synth',
      name: 'Synth',
      displayName: 'Synth',
      fontFamily: 'ABank',
      fontWeight: FontWeight.w400,
      textColor: Color(0xFFFFFFFF),
      gradientColors: [Color(0xFFFFFFFF), Color(0xFFB99BFF), Color(0xFF3CE7FF)],
      shadowColor: Color(0xAA7B2CFF),
      shadowOffset: Offset(0, 0),
      shadowBlur: 18.0,
      canvasGradient: [Color(0xFF171042), Color(0xFF27135F)],
      previewAsset: 'assets/styles/pishrafte/synth.png',
    ),
    TextStylePreset(
      id: 'acryl',
      name: 'Acryl',
      displayName: 'Acryl',
      fontFamily: 'BakbakOne',
      fontWeight: FontWeight.w400,
      textColor: Colors.white,
      shadowColor: Color(0x99000000),
      shadowOffset: Offset(4, 12),
      shadowBlur: 18.0,
      canvasColor: Color(0xFF5226B1),
      previewAsset: 'assets/styles/pishrafte/acryl.png',
    ),
    TextStylePreset(
      id: 'iron',
      name: 'Iron',
      displayName: 'Iron',
      fontFamily: 'BTitr',
      fontWeight: FontWeight.w700,
      textColor: Color(0xFF376282),
      shadowColor: Color(0xFF102133),
      shadowOffset: Offset(4, 8),
      shadowBlur: 8.0,
      canvasGradient: [Color(0xFF61707D), Color(0xFF192632)],
      canvasGradientStops: [0.06, 0.94],
      previewAsset: 'assets/styles/pishrafte/iron.png',
    ),
    TextStylePreset(
      id: 'paper',
      name: 'Paper',
      displayName: 'Paper',
      fontFamily: 'Nunito',
      fontWeight: FontWeight.w400,
      textColor: Color(0xFF0A534F),
      shadowColor: Color(0x33000000),
      shadowOffset: Offset(1, 1),
      shadowBlur: 2.0,
      canvasColor: Color(0xFFD2F0EE),
      previewAsset: 'assets/styles/pishrafte/paper.png',
    ),
    TextStylePreset(
      id: 'cake',
      name: 'Cake',
      displayName: 'Cake',
      fontFamily: 'Nunito',
      fontWeight: FontWeight.w900,
      textColor: Color(0xFF22B7AA),
      strokeColor: Colors.white,
      strokeWidth: 1.6,
      shadowColor: Color(0x88005C55),
      shadowOffset: Offset(3, 4),
      shadowBlur: 3.0,
      canvasColor: Color(0xFFE8FFFC),
      previewAsset: 'assets/styles/pishrafte/cake.png',
    ),
    TextStylePreset(
      id: 'popsicle',
      name: 'Popsicle',
      displayName: 'Popsicle',
      fontFamily: 'OleoScript',
      fontWeight: FontWeight.w700,
      textColor: Color(0xFFFF7E38),
      strokeColor: Colors.white,
      strokeWidth: 2.0,
      shadowColor: Color(0x994B30FF),
      shadowOffset: Offset(4, 6),
      shadowBlur: 0.0,
      canvasGradient: [Color(0xFF6D4BFF), Color(0xFF9A35FF)],
      previewAsset: 'assets/styles/pishrafte/popsicle.png',
    ),
    TextStylePreset(
      id: 'waffle',
      name: 'Waffle',
      displayName: 'Waffle',
      fontFamily: 'Fredoka',
      fontWeight: FontWeight.w600,
      textColor: Color(0xFFFFB14F),
      strokeColor: Color(0xFFC51D12),
      strokeWidth: 1.0,
      shadowColor: Color(0x77000000),
      shadowOffset: Offset(2, 4),
      shadowBlur: 4.0,
      canvasGradient: [Color(0xFFBD1A12), Color(0xFF98100B)],
      previewAsset: 'assets/styles/pishrafte/waffle.png',
    ),
    TextStylePreset(
      id: 'glitch',
      name: 'Glitch',
      displayName: 'Glitch',
      fontFamily: 'Inter',
      fontWeight: FontWeight.w900,
      textColor: Colors.white,
      shadowColor: Color(0xAA00E6FF),
      shadowOffset: Offset(-3, 0),
      shadowBlur: 0.0,
      canvasColor: Color(0xFF050713),
      previewAsset: 'assets/styles/pishrafte/glitch.png',
    ),
    TextStylePreset(
      id: 'neon',
      name: 'Neon',
      displayName: 'Neon',
      fontFamily: 'Poppins',
      fontWeight: FontWeight.w900,
      textColor: Color(0xFF14F195),
      canvasColor: Color(0xFF161616),
      previewAsset: 'assets/styles/pishrafte/neon.png',
    ),
    TextStylePreset(
      id: 'arcade',
      name: 'Arcade',
      displayName: 'Arcade',
      fontFamily: 'Roboto',
      fontWeight: FontWeight.w700,
      textColor: Color(0xFF33CEFF),
      canvasColor: Color(0xFF02064D),
      previewAsset: 'assets/styles/pishrafte/arcade.png',
    ),
    TextStylePreset(
      id: 'chew',
      name: 'Chew',
      displayName: 'Chew',
      fontFamily: 'Rubik',
      fontWeight: FontWeight.w800,
      textColor: Color(0xFF8EDBFF),
      shadowColor: Color(0x553891D5),
      shadowOffset: Offset(2, 4),
      shadowBlur: 4.0,
      canvasColor: Color(0xFF35B9F1),
      previewAsset: 'assets/styles/pishrafte/chew.png',
    ),
    TextStylePreset(
      id: 'licorice',
      name: 'Licorice',
      displayName: 'Licorice',
      fontFamily: 'Kalam',
      fontWeight: FontWeight.w700,
      textColor: Color(0xFF7EF23B),
      strokeColor: Colors.white,
      strokeWidth: 1.4,
      shadowColor: Color(0x8842A500),
      shadowOffset: Offset(2, 4),
      shadowBlur: 3.0,
      canvasGradient: [Color(0xFF9AFF1A), Color(0xFF74E900)],
      previewAsset: 'assets/styles/pishrafte/licorice.png',
    ),
    TextStylePreset(
      id: 'red_velvet',
      name: 'Red velvet',
      displayName: 'Red velvet',
      fontFamily: 'Chewy',
      fontWeight: FontWeight.w400,
      textColor: Color(0xFFD40000),
      strokeColor: Colors.white,
      strokeWidth: 2.0,
      shadowColor: Color(0x88000000),
      shadowOffset: Offset(4, 8),
      shadowBlur: 10.0,
      canvasColor: Color(0xFFF1B5B8),
      previewAsset: 'assets/styles/pishrafte/red_velvet.png',
    ),
  ];
}
